development:
  adapter: postgresql
  encoding: unicode
  database: ict_development
  pool: 5
  username: ict
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: ict_test
  pool: 5
  username: ict
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: ict_production
  pool: 5
  username: ict
  password:
